import Foundation

// Split from `ParityFixtureEmitter.swift`, which had reached SwiftLint's
// `file_length` cap. The boundary is behavioural rather than arbitrary:
// producing a `Fixture` (the specs, `run`, `normalize`, `encodeScenario`) stays
// there; turning fixtures into generated Kotlin lives here.
//
// The move is byte-faithful for `header`, `fixtureBlock`, `stringList`, `kdoc`
// and `assertRawStringSafe` — `kotlinSource` was decomposed but emits the same
// output. `allList(_:)` and the `all` roster it renders are NEW, not relocated;
// read the generated diff with that in mind. No `nonisolated`
// marker is needed on the extension — `PasturaHarnessKit` declares no
// `.defaultIsolation(MainActor.self)` in `Package.swift`, unlike `PasturaCore`,
// so `swift-isolation.md` Pattern 3 does not reach this target.
extension ParityFixtureEmitter {

  /// Renders every fixture as a Kotlin source file of raw-string constants.
  ///
  /// **Why generated Kotlin rather than a resource file.** No test anywhere
  /// under `shared/` reads from disk outside `jvmTest` — the two that do use
  /// `getResourceAsStream` / `java.io.File`, both JVM-only. ADR-023 Decision 5
  /// requires the Kotlin/Native `macosArm64` rung as well, and an embedded
  /// source constant is the only form that reaches it. The trade-off bought is
  /// a generated file, which is what `parity-emit --check` exists to guard.
  ///
  /// **That gate runs in CI only** — `harness-build`, next to `emit-golden
  /// --check`; no git hook builds this package, so a local commit is unguarded.
  /// Deferring it to slice 1b weighed the wrong thing — staleness in a
  /// *generated* file needs no consumer, and #1397 changed it unwatched.
  package static func kotlinSource(from fixtures: [Fixture]) throws -> String {
    var lines = header()
    for fixture in fixtures {
      try assertRawStringSafe(fixture)
      lines.append(contentsOf: fixtureBlock(fixture))
    }
    lines.append(contentsOf: allList(fixtures))
    lines.append("}")
    lines.append("")
    return lines.joined(separator: "\n")
  }

  /// The file preamble, down to and including the `Fixture` declaration.
  private static func header() -> [String] {
    [
      "// Generated by `\(regenerateCommand)` — DO NOT edit by hand.",
      "//",
      "// ADR-023 Stage-4 cross-language parity fixtures. Each entry carries the",
      "// scenario, the exact model answers the Swift Engine consumed, the event",
      "// transcript it produced, and the backend call count. `EngineParityTests`",
      "// replays the answers through the Kotlin Engine and compares.",
      "//",
      "// The transcript is `EventLineMapper`'s projection with `t` and `attempt`",
      "// pinned to 0 — see `ParityFixtureEmitter` for why that projection and not",
      "// a `SimulationEvent` encoding.",
      "",
      "package com.pastura.engine",
      "",
      "internal object ParityGolden {",
      "",
      "    /** One frozen Swift-side run. */",
      "    internal data class Fixture(",
      "        val name: String,",
      "        val scenarioJson: String,",
      "        val responses: List<String>,",
      "        val transcript: List<String>,",
      "        val callCount: Int,",
      "    )"
    ]
  }

  /// One `internal val <name>: Fixture = Fixture(...)` block.
  private static func fixtureBlock(_ fixture: Fixture) -> [String] {
    var lines = [""]
    lines.append(contentsOf: kdoc(fixture.purpose))
    lines.append("    internal val \(fixture.name): Fixture = Fixture(")
    lines.append("        name = \"\(fixture.name)\",")
    // `.trimIndent()` because Kotlin — unlike a Java text block — keeps the
    // newline after the opening `"""` and the one before the closing one.
    // Without it this one field's bytes would be `"\n" + <what Swift emitted>
    // + "\n"` while `responses` and `transcript` are exact, and the consumer
    // would have to know which fields to trim. `trimIndent` strips the blank
    // first/last lines and finds no common indentation to remove, since the
    // JSON sits at column 0.
    lines.append("        scenarioJson = \"\"\"")
    lines.append(fixture.scenarioJSON)
    lines.append("\"\"\".trimIndent(),")
    lines.append(contentsOf: stringList("responses", fixture.responses))
    lines.append(contentsOf: stringList("transcript", fixture.transcript))
    lines.append("        callCount = \(fixture.callCount),")
    lines.append("    )")
    return lines
  }

  /// The `all` roster every fixture-iterating guard reads.
  private static func allList(_ fixtures: [Fixture]) -> [String] {
    var lines = [
      "",
      "    /**",
      "     * Every fixture, so a consumer cannot silently scope itself to one.",
      "     *",
      "     * The named properties above are the readable handles; this is what",
      "     * tests iterate. A guard written over a hand-listed subset keeps",
      "     * passing when a fixture is added, and an unexercised fixture looks",
      "     * exactly like a green one.",
      "     */",
      "    internal val all: List<Fixture> = listOf("
    ]
    for fixture in fixtures {
      lines.append("        \(fixture.name),")
    }
    lines.append("    )")
    return lines
  }

  /// Renders a `listOf(...)` of raw strings, one entry per line.
  private static func stringList(_ label: String, _ values: [String]) -> [String] {
    guard !values.isEmpty else { return ["        \(label) = emptyList(),"] }
    var lines = ["        \(label) = listOf("]
    for value in values {
      lines.append("            \"\"\"\(value)\"\"\",")
    }
    lines.append("        ),")
    return lines
  }

  /// Wraps a purpose string as a KDoc block.
  private static func kdoc(_ purpose: String) -> [String] {
    var lines = ["    /**"]
    for line in purpose.split(separator: "\n", omittingEmptySubsequences: false) {
      lines.append(line.isEmpty ? "     *" : "     * \(line)")
    }
    lines.append("     */")
    return lines
  }

  /// Rejects bytes a Kotlin raw string would mangle.
  ///
  /// `"""` closes the literal early and `$` is read as template interpolation.
  /// Scenario prose is author-controlled, so this exists to fail loudly at
  /// generation time rather than emit a file that does not compile — or worse,
  /// one that compiles carrying silently different bytes.
  private static func assertRawStringSafe(_ fixture: Fixture) throws {
    let payloads = [fixture.scenarioJSON] + fixture.responses + fixture.transcript
    for payload in payloads {
      if payload.contains("\"\"\"") {
        throw ParityFixtureError.rawStringUnsafe(fixture.name, #"a """ sequence"#)
      }
      if payload.contains("$") {
        throw ParityFixtureError.rawStringUnsafe(fixture.name, "a $ (Kotlin interpolates it)")
      }
      // A payload ending in `"` abuts the closing delimiter and yields `""""`,
      // which Kotlin cannot parse. Unreachable today — every payload is a JSON
      // object ending in `}` — so this keeps the guard as wide as its own claim
      // rather than as wide as today's inputs.
      if payload.hasSuffix("\"") {
        throw ParityFixtureError.rawStringUnsafe(fixture.name, "a trailing quote")
      }
      // Symmetry, not an asserted parse failure. Kotlin's documented raw-string
      // limitation is the *trailing* quote — the opener is exactly three quotes,
      // so a fourth at the start is content. A leading quote is rejected here as
      // conservatism rather than because it is known to break the parse; the
      // claim is deliberately weaker than the trailing arm's, which is verified.
      if payload.hasPrefix("\"") {
        throw ParityFixtureError.rawStringUnsafe(fixture.name, "a leading quote")
      }
    }
    // The name is interpolated as a Kotlin *identifier* (`internal val <name>`),
    // not into a string, so it has its own way to produce a file that does not
    // compile.
    if !fixture.name.allSatisfy({ $0.isLetter || $0.isNumber || $0 == "_" }) {
      throw ParityFixtureError.rawStringUnsafe(
        fixture.name, "a non-identifier character in its name")
    }
    // `purpose` is not a raw-string payload but IS emitted into a KDoc block, so
    // it has its own way to break the build.
    if fixture.purpose.contains("*/") {
      throw ParityFixtureError.rawStringUnsafe(
        fixture.name, "a */ in its purpose (closes the KDoc)")
    }
  }
}
