// Generated by `swift run pastura-harness emit-golden --write` — DO NOT edit by hand.
//
// The bytes Swift's `Codable` conformances emit for the two types
// ADR-023 §6 measurement (v) names. Frozen here so the Kotlin parity
// suite is checked against the real wire format rather than against a
// transcription of it. See `SwiftGoldenParityTests` for what is asserted
// — `TurnOutput` decoded directly, `OutputSchema` compared under
// `Canonicalizer` normalization because its tag form diverges by design.
//
// Each constant is byte-exact **from the first `{` to the last `}`** — the
// JSON is left at column 0 rather than indented to match the surrounding
// Kotlin, because an indented copy is no longer the thing Swift produced.
//
// Not literally byte-identical, and the difference is worth stating rather
// than rounding off: a Kotlin raw string keeps the newline that follows the
// opening triple-quote and the one preceding the closing one, so every value
// here is `"\n" + <what Swift emitted> + "\n"`. Harmless for the parity
// tests, which decode rather than compare bytes — but a future assertion
// that DOES compare bytes must trim first, and would otherwise fail against
// a claim this header made.

package com.pastura.models

internal object SwiftGoldenJson {
    /**
     * The speak_all shape — one primary field.
     */
    public const val turnOutputSingleField: String = """
{
  "fields" : {
    "statement" : "Hello."
  }
}
"""

    /**
     * Primary + secondary field; key order is the encoder's, not the author's.
     */
    public const val turnOutputMultipleFields: String = """
{
  "fields" : {
    "inner_thought" : "Not really.",
    "statement" : "I agree."
  }
}
"""

    /**
     * CJK + emoji — the value class that crashed the sampler in #597/#599.
     */
    public const val turnOutputMultibyte: String = """
{
  "fields" : {
    "reason" : "多バイト値",
    "statement" : "こんにちは 🐑"
  }
}
"""

    /**
     * Degenerate but legal: no fields at all.
     */
    public const val turnOutputEmptyFields: String = """
{
  "fields" : {

  }
}
"""

    /**
     * `rawText` is set on the Swift value and must NOT appear in the bytes — it is provenance metadata excluded from the wire shape by a custom CodingKeys. Freezing it here makes that exclusion a fact the Kotlin side can rely on rather than a Swift-internal detail.
     */
    public const val turnOutputWithRawText: String = """
{
  "fields" : {
    "statement" : "provenance"
  }
}
"""

    /**
     * The speak_all schema — a single `.string` field.
     */
    public const val outputSchemaStringKind: String = """
{
  "fields" : [
    {
      "kind" : {
        "string" : {

        }
      },
      "name" : "statement"
    }
  ]
}
"""

    /**
     * The choose schema — `.choice` carries no option payload by design.
     */
    public const val outputSchemaChoiceKind: String = """
{
  "fields" : [
    {
      "kind" : {
        "choice" : {

        }
      },
      "name" : "action"
    },
    {
      "kind" : {
        "string" : {

        }
      },
      "name" : "reason"
    }
  ]
}
"""

    /**
     * relationship_update — exercises `voteAgainst` and `actionDeltas` (#910).
     */
    public const val phaseRelationshipUpdate: String = """
{
  "actionDeltas" : {
    "betray" : -2,
    "cooperate" : 1
  },
  "type" : "relationship_update",
  "voteAgainst" : -1
}
"""

    /**
     * narrate — exercises `narrator`, a CJK voice descriptor (#909).
     */
    public const val phaseNarrate: String = """
{
  "narrator" : "熱血なスポーツ実況",
  "type" : "narrate"
}
"""

    /**
     * event_inject — exercises `noRepeat` draw-without-replacement (#1006).
     */
    public const val phaseEventInjectNoRepeat: String = """
{
  "eventVariable" : "current_event",
  "noRepeat" : true,
  "type" : "event_inject"
}
"""

    /**
     * score_calc/pairwise_payoff — exercises `payoff`, nesting PayoffRule (ADR-027).
     */
    public const val phasePairwisePayoff: String = """
{
  "logic" : "pairwise_payoff",
  "payoff" : [
    {
      "points" : [
        3,
        3
      ],
      "when" : [
        "cooperate",
        "cooperate"
      ]
    },
    {
      "points" : [
        0,
        5
      ],
      "when" : [
        "cooperate",
        "betray"
      ]
    }
  ],
  "type" : "score_calc"
}
"""

    /**
     * A single ADR-027 payoff row; asymmetric points make a when/points swap detectable.
     */
    public const val payoffRuleBasic: String = """
{
  "points" : [
    0,
    5
  ],
  "when" : [
    "cooperate",
    "betray"
  ]
}
"""
}
