// Generated by `swift run pastura-harness emit-golden --write` — DO NOT edit by hand.
//
// The bytes Swift's `Codable` conformances emit for the two types
// ADR-023 §6 measurement (v) names. Frozen here so Kotlin's decoders are
// checked against the real wire format rather than against a
// transcription of it. See `SwiftGoldenParityTests` for what is asserted,
// including the cases Kotlin currently CANNOT decode.
//
// Each constant is byte-exact — the JSON is left at column 0 rather than
// indented to match the surrounding Kotlin, because an indented copy is no
// longer the thing Swift produced.

package com.pastura.models

internal object SwiftGoldenJson {
    /**
     * The speak_all shape — one primary field.
     */
    public const val turnOutputSingleField: String = """
{
  "fields" : {
    "statement" : "Hello."
  }
}
"""

    /**
     * Primary + secondary field; key order is the encoder's, not the author's.
     */
    public const val turnOutputMultipleFields: String = """
{
  "fields" : {
    "inner_thought" : "Not really.",
    "statement" : "I agree."
  }
}
"""

    /**
     * CJK + emoji — the value class that crashed the sampler in #597/#599.
     */
    public const val turnOutputMultibyte: String = """
{
  "fields" : {
    "reason" : "多バイト値",
    "statement" : "こんにちは 🐑"
  }
}
"""

    /**
     * Degenerate but legal: no fields at all.
     */
    public const val turnOutputEmptyFields: String = """
{
  "fields" : {

  }
}
"""

    /**
     * `rawText` is set on the Swift value and must NOT appear in the bytes — it is provenance metadata excluded from the wire shape by a custom CodingKeys. Freezing it here makes that exclusion a fact the Kotlin side can rely on rather than a Swift-internal detail.
     */
    public const val turnOutputWithRawText: String = """
{
  "fields" : {
    "statement" : "provenance"
  }
}
"""

    /**
     * The speak_all schema — a single `.string` field.
     */
    public const val outputSchemaStringKind: String = """
{
  "fields" : [
    {
      "kind" : {
        "string" : {

        }
      },
      "name" : "statement"
    }
  ]
}
"""

    /**
     * The choose schema — `.choice` carries no option payload by design.
     */
    public const val outputSchemaChoiceKind: String = """
{
  "fields" : [
    {
      "kind" : {
        "choice" : {

        }
      },
      "name" : "action"
    },
    {
      "kind" : {
        "string" : {

        }
      },
      "name" : "reason"
    }
  ]
}
"""
}
