#!/usr/bin/env python3
"""Generate docs/design/navigation-map.md from the root-stack navigation source.

Derives the screen graph from code so the committed map never drifts:

- **Nodes**: ``Route`` enum cases parsed from ``Pastura/Pastura/App/Router.swift``
  plus a synthetic ``home`` root (HomeView owns the stack root; it is not a
  Route case).
- **Edges**: callsites of ``NavigationLink(value: Route.X ...)``,
  ``router.push(.X)`` (forward-looking — zero callsites today), and
  ``router.pushIfOnTop(... next: .X ...)`` scanned across ``Views/`` and
  ``App/``. Matching is whole-file with ``\\s``-tolerant regexes because
  swift-format freely breaks these calls across lines (see
  ``.claude/rules/ci-workflows.md`` — token presence over single-line grep);
  comments are stripped first so doc-comment examples never become edges.
- **Helper indirection**: ``NavigationLink(value: someHelper())`` carries no
  Route token. Known helpers are attributed via ``MANUAL_EDGES``; unknown
  helpers fail ``--check`` with "manual edge attribution required" rather
  than silently dropping an edge.

Sheets / fullScreenCover are intentionally absent: ``AppRouter`` manages the
root NavigationStack only (``.claude/rules/navigation.md``); sheet-owned
flows are out of scope for this map.

Modes:
  (default)     rewrite docs/design/navigation-map.md
  --check       regenerate in memory and diff against the committed file;
                nonzero exit on drift (CI: navigation-map-drift job)
  --self-test   run embedded regression fixtures; nonzero exit on failure

Screenshot names in the node table reference the *gitignored* outputs of
``scripts/ui-tour.sh`` by name only (never by link) — see
``docs/design/screenshots/README.md`` for regeneration.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ROUTER_FILE = REPO_ROOT / "Pastura/Pastura/App/Router.swift"
SCAN_DIRS = (
    REPO_ROOT / "Pastura/Pastura/Views",
    REPO_ROOT / "Pastura/Pastura/App",
)
OUTPUT_FILE = REPO_ROOT / "docs/design/navigation-map.md"

# Definition / infra files: Router.swift declares the enum (node source, not
# an edge source); AppRouter.swift carries the real pushIfOnTop SIGNATURE
# (comment-stripping alone would not remove it); RouteHint.swift quotes
# Route/case examples in doc comments. None of them navigates.
EDGE_SOURCE_EXCLUDE = {"Router.swift", "AppRouter.swift", "RouteHint.swift"}

# Callsite file -> screen node. A file that matches a nav token but is not
# listed here fails --check, forcing a conscious attribution update instead
# of a silently mis-attributed (or dropped) edge.
FILE_TO_SCREEN = {
    "Pastura/Pastura/Views/Home/HomeView.swift": "home",
    "Pastura/Pastura/Views/ScenarioDetail/ScenarioDetailView.swift": "scenarioDetail",
    "Pastura/Pastura/Views/ScenarioDetail/ScenarioDetailView+Sections.swift": "scenarioDetail",
    "Pastura/Pastura/Views/Results/ResultsView.swift": "results",
    "Pastura/Pastura/Views/Community/SharedScenarios/SharedScenariosListView.swift": "sharedScenarios",
    "Pastura/Pastura/Views/Community/SharedScenarios/GalleryScenarioDetailView.swift": "galleryScenarioDetail",
}

# (source screen, target route case, label) for edges the scanner cannot
# see because the Route value is built by a helper function.
MANUAL_EDGES = [
    ("home", "editor", "via newScenarioRoute()"),
]
# Helper identifiers covered by MANUAL_EDGES. NavigationLink(value: <id>())
# with an identifier outside this set is an error.
KNOWN_HELPERS = {"newScenarioRoute"}

# Display label, screenshot-tour anchor identifier, and ui-tour.sh
# screenshot name per node. Screenshot "None" renders as deferred (see
# docs/design/screenshots/README.md "Deferred" section).
NODE_INFO = {
    "home": ("Home", "home.scenarioListCell.*", "01-home"),
    "scenarioDetail": ("Scenario Detail", "scenarioDetail.list", "02-scenario-detail"),
    "editor": ("Scenario Editor", "editor.titleField", "03-editor"),
    "simulation": ("Simulation", None, None),
    "results": ("Past Results", "results.list", "07-results"),
    "resultDetail": ("Result Detail", "resultDetail.timeline", "08-result-detail"),
    "sharedScenarios": ("Shared Scenarios", "sharedScenarios.galleryCell.*", "04-shared-scenarios"),
    "galleryScenarioDetail": ("Gallery Scenario Detail", "galleryDetail.tryButton", "05-gallery-detail"),
    "settings": ("Settings", "settings.licensesLink", "06-settings"),
}

HEADER = """\
<!-- Generated by scripts/generate-navigation-map.py — DO NOT edit by hand.
     Regenerate: python3 scripts/generate-navigation-map.py
     Drift guard: python3 scripts/generate-navigation-map.py --check (CI: navigation-map-drift) -->
"""

# --- parsing -----------------------------------------------------------------

BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.S)
LINE_COMMENT_RE = re.compile(r"//[^\n]*")
ROUTE_CASE_RE = re.compile(r"^\s*case\s+(\w+)", re.M)
# \s matches newlines: swift-format may break after "NavigationLink(" and
# after "value:" (both shapes exist on main today).
LINK_ROUTE_RE = re.compile(r"NavigationLink\(\s*value:\s*Route\.(\w+)")
LINK_HELPER_RE = re.compile(r"NavigationLink\(\s*value:\s*(?!Route\.)(\w+)\(")
PUSH_RE = re.compile(r"router\.push\(\s*(?:Route)?\.(\w+)")
# Non-greedy across the expected: argument (which contains nested parens).
# The tempered span refuses to cross into a following pushIfOnTop( call, so
# a hypothetical future next:-less overload can't bridge two calls and
# mis-attribute the second call's target.
PUSH_IF_ON_TOP_RE = re.compile(r"pushIfOnTop\((?:(?!pushIfOnTop\().)*?next:\s*\.(\w+)", re.S)


def strip_comments(swift: str) -> str:
    """Remove block and line comments. Line-based ``//`` stripping can eat
    string-literal tails (e.g. ``"stub://..."``) — safe here because removal
    can only ever *hide* tokens inside strings, never invent nav tokens."""
    return LINE_COMMENT_RE.sub("", BLOCK_COMMENT_RE.sub("", swift))


def parse_route_cases(router_source: str) -> list[str]:
    """Route case names in declaration order. Router.swift is dedicated to
    the Route enum, so every top-level ``case`` line is a route."""
    return ROUTE_CASE_RE.findall(strip_comments(router_source))


def scan_file_edges(rel_path: str, swift: str) -> tuple[list[tuple[str, str, str]], list[str]]:
    """Return (edges, errors) for one file. Edge = (source, target, label)."""
    stripped = strip_comments(swift)
    targets = LINK_ROUTE_RE.findall(stripped)
    targets += PUSH_RE.findall(stripped)
    targets += PUSH_IF_ON_TOP_RE.findall(stripped)
    helpers = [h for h in LINK_HELPER_RE.findall(stripped) if h not in KNOWN_HELPERS]

    errors = []
    if not targets and not helpers:
        return [], errors

    source = FILE_TO_SCREEN.get(rel_path)
    if source is None:
        errors.append(
            f"{rel_path}: navigation callsite found but file is not in "
            "FILE_TO_SCREEN — add an attribution entry in "
            "scripts/generate-navigation-map.py"
        )
        return [], errors
    for helper in helpers:
        errors.append(
            f"{rel_path}: NavigationLink(value: {helper}(...)) — manual edge "
            "attribution required: add the helper to KNOWN_HELPERS and its "
            "edge to MANUAL_EDGES in scripts/generate-navigation-map.py"
        )
    return [(source, target, "") for target in targets], errors


def collect_edges() -> tuple[list[tuple[str, str, str]], list[str]]:
    edges: list[tuple[str, str, str]] = []
    errors: list[str] = []
    for scan_dir in SCAN_DIRS:
        for path in sorted(scan_dir.rglob("*.swift")):
            if path.name in EDGE_SOURCE_EXCLUDE:
                continue
            rel = path.relative_to(REPO_ROOT).as_posix()
            file_edges, file_errors = scan_file_edges(rel, path.read_text(encoding="utf-8"))
            edges.extend(file_edges)
            errors.extend(file_errors)
    edges.extend(MANUAL_EDGES)
    return edges, errors


# --- emission ----------------------------------------------------------------


def emit_markdown(route_cases: list[str], edges: list[tuple[str, str, str]]) -> str:
    nodes = ["home"] + route_cases
    incoming_sources: dict[str, set[str]] = {n: set() for n in nodes}
    for source, target, _ in edges:
        if target in incoming_sources:
            incoming_sources[target].add(source)

    lines = [HEADER]
    lines.append("# Navigation Map — root NavigationStack\n")
    lines.append(
        "Screen graph of the root stack, generated from `Route` enum cases and\n"
        "`NavigationLink` / `router.push` / `pushIfOnTop` callsites. Sheets and\n"
        "fullScreenCover flows are out of scope (`AppRouter` manages the root\n"
        "stack only — see `.claude/rules/navigation.md`). `home` is the stack\n"
        "root (`HomeView`), not a `Route` case.\n"
    )
    lines.append("```mermaid")
    lines.append("flowchart TD")
    for node in nodes:
        label = NODE_INFO.get(node, (node, None, None))[0]
        shape = f"([{label}])" if node == "home" else f'["{label}"]'
        lines.append(f"  {node}{shape}")
    seen = set()
    for source, target, label in sorted(edges):
        if (source, target, label) in seen:
            continue
        seen.add((source, target, label))
        arrow = f' -->|"{label}"| ' if label else " --> "
        lines.append(f"  {source}{arrow}{target}")
    lines.append("```\n")

    lines.append("## Screens\n")
    lines.append(
        "Screenshot names refer to `scripts/ui-tour.sh` outputs (gitignored —\n"
        "regenerate to view; `docs/design/screenshots/README.md`). Anchors are\n"
        "the tour's per-screen wait identifiers.\n"
    )
    lines.append("| Node | Screen | Pushed from | Tour anchor | Screenshot |")
    lines.append("|------|--------|-------------|-------------|------------|")
    for node in nodes:
        label, anchor, shot = NODE_INFO.get(node, (node, None, None))
        sources = ", ".join(f"`{s}`" for s in sorted(incoming_sources[node])) or "— (stack root)"
        anchor_cell = f"`{anchor}`" if anchor else "—"
        shot_cell = f"`{shot}.png`" if shot else "deferred — see `screenshots/README.md`"
        lines.append(f"| `{node}` | {label} | {sources} | {anchor_cell} | {shot_cell} |")
    lines.append("")
    return "\n".join(lines)


def generate() -> tuple[str, list[str]]:
    route_cases = parse_route_cases(ROUTER_FILE.read_text(encoding="utf-8"))
    edges, errors = collect_edges()
    known = set(["home"] + route_cases)
    for source, target, _ in edges:
        if target not in known:
            errors.append(f"edge target '.{target}' is not a Route case — scanner or Route drift")
        if source not in known:
            errors.append(f"edge source '{source}' is not a known node")
    missing_info = [n for n in known if n not in NODE_INFO]
    if missing_info:
        errors.append(
            f"NODE_INFO missing entries for: {', '.join(sorted(missing_info))} — "
            "add label/anchor/screenshot rows in scripts/generate-navigation-map.py"
        )
    return emit_markdown(route_cases, edges), errors


# --- self-test ---------------------------------------------------------------


def self_test() -> int:
    failures = []

    def check(name: str, condition: bool):
        if not condition:
            failures.append(name)

    # Doc-comment tokens must never become edges or nodes.
    commented = "/// Example: `router.push(.settings)` no-ops here.\n// case foo\n"
    check("comment: zero edges", scan_file_edges("Pastura/Pastura/Views/Home/HomeView.swift", commented)[0] == [])
    check("comment: zero nodes", parse_route_cases("/// enum Route { case scenarioDetail(id: String) }\n") == [])

    # Exact production wrap from GalleryScenarioDetailView (next: and the
    # case on separate physical lines, nested parens in expected:).
    push_wrap = (
        "router.pushIfOnTop(\n"
        "  expected: .galleryScenarioDetail(scenario: scenario),\n"
        "  next: .scenarioDetail(\n"
        "    scenarioId: scenarioId,\n"
        "    initialName: .init(name)))\n"
    )
    edges, errs = scan_file_edges(
        "Pastura/Pastura/Views/Community/SharedScenarios/GalleryScenarioDetailView.swift", push_wrap
    )
    check("pushIfOnTop wrap: one scenarioDetail edge", edges == [("galleryScenarioDetail", "scenarioDetail", "")] and not errs)

    # Exact production wrap from ScenarioDetailView (line break after
    # "NavigationLink(" AND after "value:"-adjacent Route call).
    link_wrap = (
        "NavigationLink(\n"
        "  value: Route.simulation(\n"
        "    scenarioId: scenarioId,\n"
        "    initialName: .init(scenario.name)\n"
        "  )\n"
        ") { Label(\"Run\", systemImage: \"play.fill\") }\n"
    )
    edges, errs = scan_file_edges("Pastura/Pastura/Views/ScenarioDetail/ScenarioDetailView.swift", link_wrap)
    check("NavigationLink wrap: one simulation edge", edges == [("scenarioDetail", "simulation", "")] and not errs)

    # Unknown helper must error, never silently drop.
    helper = "NavigationLink(value: mysteryRoute()) { Text(\"x\") }\n"
    edges, errs = scan_file_edges("Pastura/Pastura/Views/Home/HomeView.swift", helper)
    check("unknown helper: error", edges == [] and len(errs) == 1 and "manual edge attribution" in errs[0])

    # Known helper produces no scanner edge (covered by MANUAL_EDGES instead).
    known_helper = "NavigationLink(value: newScenarioRoute()) { Text(\"x\") }\n"
    edges, errs = scan_file_edges("Pastura/Pastura/Views/Home/HomeView.swift", known_helper)
    check("known helper: no edge, no error", edges == [] and errs == [])

    # Un-attributed file with a real edge must error.
    edges, errs = scan_file_edges("Pastura/Pastura/Views/Settings/SettingsView.swift", "NavigationLink(value: Route.editor()) {}\n")
    check("unknown file: attribution error", edges == [] and len(errs) == 1 and "FILE_TO_SCREEN" in errs[0])

    for name in failures:
        print(f"SELF-TEST FAIL: {name}", file=sys.stderr)
    print(f"self-test: {7 - len(failures)}/7 passed")
    return 1 if failures else 0


# --- main --------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="diff regenerated output against the committed file")
    parser.add_argument("--self-test", action="store_true", help="run embedded regression fixtures")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    content, errors = generate()
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if args.check:
        committed = OUTPUT_FILE.read_text(encoding="utf-8") if OUTPUT_FILE.exists() else ""
        if committed != content:
            print(
                "ERROR: docs/design/navigation-map.md is stale — regenerate with\n"
                "  python3 scripts/generate-navigation-map.py",
                file=sys.stderr,
            )
            import difflib

            sys.stderr.writelines(
                difflib.unified_diff(
                    committed.splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile="committed",
                    tofile="regenerated",
                )
            )
            return 1
        print("navigation-map: up to date")
        return 0

    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
