import Foundation
import Testing

@testable import Pastura

/// Drift-detection tests for Swift-generated cross-language baselines
/// (Issue #220 W2 PR-B item 4).
///
/// **Contract**: every Swift-generated baseline JSON file under
/// `shared/models/src/commonTest/resources/baselines/` must byte-equal the
/// in-memory regeneration via `RoundtripHelper`. The Kotlin equivalence
/// harness (`CanonicalEquivalenceTests`) reads the committed files; if
/// Swift ever drifts (Codable synthesis change, new field added, encoder
/// option flip), this suite fires before the Kotlin side gets a chance to
/// silently misinterpret.
///
/// **Regeneration**: set `PASTURA_REGENERATE_BASELINES=1` and run
/// `regenerateAllBaselines`. The test rewrites every Swift-generated
/// baseline to disk; review the diff before committing.
///
/// **Hand-written micro-fixtures** under `baselines/_micro/` are NOT
/// regenerated by this suite — they exist as canonicalizer inputs (Q6)
/// that exercise null-vs-omit divergence that Swift `JSONEncoder` would
/// never produce on its own (default-omits nil). Their drift is monitored
/// by the Kotlin equivalence harness directly.
@Suite("Roundtrip baselines (Swift-generated)", .timeLimit(.minutes(1)))
struct RoundtripBaselineTests {

  // MARK: - Preset scenarios (4 cases)

  @Test(
    "prisoners_dilemma baseline matches committed file", arguments: RoundtripHelper.basePresetNames)
  func presetBaselineMatchesCommitted(presetName: String) throws {
    let regenerated = try RoundtripHelper.encodedScenarioBaseline(presetName: presetName)
    let committed = try RoundtripHelper.readBaseline(name: presetName)
    #expect(
      regenerated == committed,
      """
      Baseline drift detected for \(presetName).
      Run \
      `PASTURA_REGENERATE_BASELINES=1 scripts/xcodebuild.sh test \
      -only-testing PasturaTests/RoundtripBaselineTests/regenerateAllBaselines` \
      then review the diff and re-commit.
      """)
  }

  // MARK: - Synthetic fixtures

  @Test("gallery_index baseline matches committed file")
  func galleryIndexBaselineMatchesCommitted() throws {
    let regenerated = try RoundtripHelper.encodedGalleryIndexBaseline()
    let committed = try RoundtripHelper.readBaseline(name: "gallery_index")
    #expect(regenerated == committed, "gallery_index drift — see regenerate hint above")
  }

  @Test("code_phase_event_payload baseline matches committed file")
  func codePhaseEventPayloadBaselineMatchesCommitted() throws {
    let regenerated = try RoundtripHelper.encodedCodePhaseEventPayloadsBaseline()
    let committed = try RoundtripHelper.readBaseline(name: "code_phase_event_payload")
    #expect(regenerated == committed, "code_phase_event_payload drift — see regenerate hint above")
  }

  // MARK: - Q6 day-1 sanity (eventInjected miss case)

  /// Pins Swift's encoding behaviour for `eventInjected(event: nil)`.
  /// The whole canonicalizer's null-omit Stage 1 turns on this being
  /// stable — if a future Swift Foundation release changes the
  /// auto-synth Codable to emit `"event":null` explicitly, the Kotlin
  /// equivalence harness's canonical form would diverge. This test
  /// fires first.
  @Test("eventInjected miss case omits inner event key (Swift default Codable)")
  func eventInjectedMissCaseOmitsInnerKey() throws {
    let payload = CodePhaseEventPayload.eventInjected(event: nil)
    let enc = JSONEncoder()
    enc.outputFormatting = .sortedKeys
    let data = try enc.encode(payload)
    let text = String(data: data, encoding: .utf8)
    #expect(text == #"{"eventInjected":{}}"#, "Got: \(text ?? "nil")")
  }

  // MARK: - Hand-written micro-fixture sanity

  /// The 2 hand-written micro-fixtures under `_micro/` should be present
  /// in the repository. This test just asserts existence — content
  /// validation lives in the Kotlin equivalence harness, which is the
  /// consumer that needs them.
  @Test("hand-written null-omit micro-fixtures are present")
  func microFixturesPresent() throws {
    let microDir = RoundtripHelper.baselineDir
      .appendingPathComponent("_micro", isDirectory: true)
    let explicit = microDir.appendingPathComponent("simlang_explicit_null.json")
    let omitted = microDir.appendingPathComponent("simlang_omitted.json")
    let readme = microDir.appendingPathComponent("README.md")
    #expect(FileManager.default.fileExists(atPath: explicit.path))
    #expect(FileManager.default.fileExists(atPath: omitted.path))
    #expect(FileManager.default.fileExists(atPath: readme.path))
  }

  // MARK: - Regeneration (always-disabled by default)

  /// Rewrites every Swift-generated baseline. **Always disabled.** To
  /// deliberately re-pin shapes, remove the `.disabled(...)` trait
  /// temporarily, run the suite once (`scripts/xcodebuild.sh test
  /// -only-testing PasturaTests/RoundtripBaselineTests`), review the
  /// resulting diff under `shared/models/src/commonTest/resources/baselines/`,
  /// re-add the trait, then commit.
  ///
  /// Why not env-gated: xcodebuild's xctest runner runs in a separate
  /// process with a sanitized environment. Shell-level env vars do not
  /// reach `ProcessInfo.processInfo.environment` reliably, so a
  /// `.disabled(if: ProcessInfo.../*PASTURA_REGENERATE_BASELINES*/ != "1")`
  /// would never enable. Hand-toggling the trait is the only mechanism
  /// that survives the xctest boundary, and it doubles as the review gate
  /// (the diff in the trait edit signals reviewer attention).
  ///
  /// Hand-written `_micro/` fixtures are NOT touched by this test.
  @Test(
    "Regenerate all Swift-generated baselines",
    .disabled("Remove this trait temporarily to regenerate (see doc above)."))
  func regenerateAllBaselines() throws {
    for name in RoundtripHelper.basePresetNames {
      try RoundtripHelper.writeBaseline(
        try RoundtripHelper.encodedScenarioBaseline(presetName: name),
        name: name)
    }
    try RoundtripHelper.writeBaseline(
      try RoundtripHelper.encodedGalleryIndexBaseline(),
      name: "gallery_index")
    try RoundtripHelper.writeBaseline(
      try RoundtripHelper.encodedCodePhaseEventPayloadsBaseline(),
      name: "code_phase_event_payload")
  }
}
