import Foundation
import Testing

@testable import Pastura

/// Drift-detection tests for Swift-generated cross-language baselines
/// (Issue #220 W2 PR-B item 4).
///
/// **Contract**: every Swift-generated baseline JSON file under
/// `shared/models/src/commonTest/resources/baselines/` must byte-equal the
/// in-memory regeneration via `RoundtripHelper`. The Kotlin equivalence
/// harness (`CanonicalEquivalenceTests`) reads the committed files; if
/// Swift ever drifts (Codable synthesis change, new field added, encoder
/// option flip), this suite fires before the Kotlin side gets a chance to
/// silently misinterpret.
///
/// **Regeneration**: temporarily remove the `.disabled(...)` trait on
/// `regenerateAllBaselines` (see its doc comment for rationale), run that
/// test once, review the diff, then re-add the trait before commit.
///
/// **Hand-written micro-fixtures** under `baselines/_micro/` are NOT
/// regenerated by this suite — they exist as canonicalizer inputs (Q6)
/// that exercise null-vs-omit divergence that Swift `JSONEncoder` would
/// never produce on its own (default-omits nil). Their drift is monitored
/// by the Kotlin equivalence harness directly.
@Suite("Roundtrip baselines (Swift-generated)", .timeLimit(.minutes(1)))
struct RoundtripBaselineTests {

  // MARK: - Preset scenarios (4 cases)

  @Test(
    "prisoners_dilemma baseline matches committed file", arguments: RoundtripHelper.basePresetNames)
  func presetBaselineMatchesCommitted(presetName: String) throws {
    let regenerated = try RoundtripHelper.encodedScenarioBaseline(presetName: presetName)
    let committed = try RoundtripHelper.readBaseline(name: presetName)
    #expect(
      regenerated == committed,
      """
      Baseline drift detected for \(presetName).
      Temporarily remove the `.disabled(...)` trait on \
      `regenerateAllBaselines`, run the RoundtripBaselineTests suite once, \
      review the diff under shared/models/src/commonTest/resources/baselines/, \
      re-add the trait, then commit.
      """)
  }

  // MARK: - YAML-shape baselines (lossless raw-parse; W4 PR-C)

  /// Drift guard for the lossless YAML-shape baselines consumed by the Kotlin
  /// cross-language fidelity harness. If a curator edits a preset's YAML, the
  /// committed `yaml-baselines/<preset>.yaml.json` goes stale and the Kotlin
  /// snakeyaml-vs-Yams comparison silently tests an old shape — this fires
  /// first. Regenerate via the same `.disabled`-trait toggle as the other
  /// baselines (see `regenerateAllBaselines`).
  @Test(
    "YAML-shape baseline matches committed file", arguments: RoundtripHelper.basePresetNames)
  func yamlShapeBaselineMatchesCommitted(presetName: String) throws {
    let regenerated = try RoundtripHelper.encodedYamlShapeBaseline(presetName: presetName)
    let committed = try RoundtripHelper.readYamlShapeBaseline(name: presetName)
    #expect(
      regenerated == committed,
      """
      YAML-shape baseline drift for \(presetName). The live preset YAML no \
      longer matches the committed lossless parse. Temporarily remove the \
      `.disabled(...)` trait on `regenerateAllBaselines`, run the suite once, \
      review the diff under shared/models/src/commonTest/resources/yaml-baselines/, \
      re-add the trait, then commit.
      """)
  }

  /// Pins the Yams `Any` → JSON scalar mapping the Kotlin equivalence claim
  /// rests on. The load-bearing assertion is `aBool: true` → JSON `true` (NOT
  /// `1`): Yams bridges scalars through `NSNumber`, so without the `is Bool`
  /// guard in `RoundtripHelper.yamlValueToJSONObject` a real boolean
  /// (`exclude_self: true` in word_wolf) would launder into an integer and the
  /// cross-language fidelity test would pass against a wrong baseline. Also
  /// pins int / float / string / null so a regression in any branch fails here
  /// rather than as an opaque Kotlin byte-diff.
  @Test("YAML dumper preserves scalar types (bool ≠ int)")
  func yamlDumperPreservesScalarTypes() throws {
    let yaml = """
      aBool: true
      anInt: 5
      aFloat: 0.5
      aString: hello
      aNull: null
      nested:
        inner: 1
      """
    let data = try RoundtripHelper.canonicalYAMLShapeJSON(yaml: yaml)
    let text = try #require(String(bytes: data, encoding: .utf8))
    // `.sortedKeys` + `.prettyPrinted` emit `"key" : value`.
    #expect(text.contains("\"aBool\" : true"), "bool must stay bool, not 1. Got:\n\(text)")
    #expect(text.contains("\"anInt\" : 5"))
    #expect(text.contains("\"aFloat\" : 0.5"))
    #expect(text.contains("\"aString\" : \"hello\""))
    #expect(text.contains("\"aNull\" : null"))
    #expect(text.contains("\"inner\" : 1"))
  }

  // MARK: - Synthetic fixtures

  @Test("gallery_index baseline matches committed file")
  func galleryIndexBaselineMatchesCommitted() throws {
    let regenerated = try RoundtripHelper.encodedGalleryIndexBaseline()
    let committed = try RoundtripHelper.readBaseline(name: "gallery_index")
    #expect(regenerated == committed, "gallery_index drift — see regenerate hint above")
  }

  @Test("code_phase_event_payload baseline matches committed file")
  func codePhaseEventPayloadBaselineMatchesCommitted() throws {
    let regenerated = try RoundtripHelper.encodedCodePhaseEventPayloadsBaseline()
    let committed = try RoundtripHelper.readBaseline(name: "code_phase_event_payload")
    #expect(regenerated == committed, "code_phase_event_payload drift — see regenerate hint above")
  }

  // MARK: - Q6 day-1 sanity (eventInjected miss case)

  /// Pins Swift's encoding behaviour for `eventInjected(event: nil)`.
  /// The whole canonicalizer's null-omit Stage 1 turns on this being
  /// stable — if a future Swift Foundation release changes the
  /// auto-synth Codable to emit `"event":null` explicitly, the Kotlin
  /// equivalence harness's canonical form would diverge. This test
  /// fires first.
  @Test("eventInjected miss case omits inner event key (Swift default Codable)")
  func eventInjectedMissCaseOmitsInnerKey() throws {
    let payload = CodePhaseEventPayload.eventInjected(event: nil)
    let enc = JSONEncoder()
    enc.outputFormatting = .sortedKeys
    let data = try enc.encode(payload)
    let text = String(data: data, encoding: .utf8)
    #expect(text == #"{"eventInjected":{}}"#, "Got: \(text ?? "nil")")
  }

  // MARK: - Hand-written micro-fixture sanity

  /// The 2 hand-written micro-fixtures under `_micro/` should be present
  /// in the repository. This test just asserts existence — content
  /// validation lives in the Kotlin equivalence harness, which is the
  /// consumer that needs them.
  @Test("hand-written null-omit micro-fixtures are present")
  func microFixturesPresent() throws {
    let microDir = RoundtripHelper.baselineDir
      .appendingPathComponent("_micro", isDirectory: true)
    let explicit = microDir.appendingPathComponent("simlang_explicit_null.json")
    let omitted = microDir.appendingPathComponent("simlang_omitted.json")
    let readme = microDir.appendingPathComponent("README.md")
    #expect(FileManager.default.fileExists(atPath: explicit.path))
    #expect(FileManager.default.fileExists(atPath: omitted.path))
    #expect(FileManager.default.fileExists(atPath: readme.path))
  }

  // MARK: - Regeneration (always-disabled by default)

  /// Rewrites every Swift-generated baseline. **Always disabled.** To
  /// deliberately re-pin shapes, remove the `.disabled(...)` trait
  /// temporarily, run the suite once (`scripts/xcodebuild.sh test
  /// -only-testing PasturaTests/RoundtripBaselineTests`), review the
  /// resulting diff under `shared/models/src/commonTest/resources/baselines/`,
  /// re-add the trait, then commit.
  ///
  /// Why not env-gated: xcodebuild's xctest runner runs in a separate
  /// process with a sanitized environment. Shell-level env vars do not
  /// reach `ProcessInfo.processInfo.environment` reliably, so a
  /// `.disabled(if: ProcessInfo.../*PASTURA_REGENERATE_BASELINES*/ != "1")`
  /// would never enable. Hand-toggling the trait is the only mechanism
  /// that survives the xctest boundary, and it doubles as the review gate
  /// (the diff in the trait edit signals reviewer attention).
  ///
  /// Hand-written `_micro/` fixtures are NOT touched by this test.
  @Test(
    "Regenerate all Swift-generated baselines",
    .disabled("Remove this trait temporarily to regenerate (see doc above)."))
  func regenerateAllBaselines() throws {
    for name in RoundtripHelper.basePresetNames {
      try RoundtripHelper.writeBaseline(
        try RoundtripHelper.encodedScenarioBaseline(presetName: name),
        name: name)
    }
    try RoundtripHelper.writeBaseline(
      try RoundtripHelper.encodedGalleryIndexBaseline(),
      name: "gallery_index")
    try RoundtripHelper.writeBaseline(
      try RoundtripHelper.encodedCodePhaseEventPayloadsBaseline(),
      name: "code_phase_event_payload")
    // Lossless YAML-shape baselines (W4 PR-C) — raw Yams parse, distinct from
    // the lossy ScenarioLoader baselines written above.
    for name in RoundtripHelper.basePresetNames {
      try RoundtripHelper.writeYamlShapeBaseline(
        try RoundtripHelper.encodedYamlShapeBaseline(presetName: name),
        name: name)
    }
  }
}
