import Foundation

/// Content blocklist categories aligned with the OpenAI Moderation taxonomy.
///
/// Used to partition patterns between input validation (authoring time)
/// and output filtering (LLM response time). See ``ContentBlocklist`` for
/// the input/output policy and ADR-005 §10.1 for the rationale.
nonisolated enum BlockedCategory: String, Decodable {
  case harassment
  case hate
  case profanity
  case sexual
  case violence
}

/// A single blocklist entry — the literal pattern matched against text and
/// the category it belongs to.
nonisolated struct BlockedPattern: Decodable {
  let term: String
  let contentCategory: BlockedCategory
}

/// Shared blocklist resource used by both ``ScenarioContentValidator`` (input
/// validation) and ``ContentFilter`` (output filtering).
///
/// Per ADR-005 §4.4, the bundled file at
/// `Pastura/Pastura/Resources/ContentBlocklist.json` is the runtime source
/// of truth. The companion `docs/blocklist/source.json` carries richer
/// metadata (lang, source) that does not ship to the bundle; the runtime
/// file is generated by `scripts/build-blocklist.sh`.
///
/// Per ADR-005 §10.1 (2026-04-27 amendment), ``inputPatterns`` excludes the
/// ``BlockedCategory/violence`` category; ``outputPatterns`` includes all
/// categories. This realises the input/output policy split that resolves
/// the gallery curation contradiction with ethics/roleplay scenarios whose
/// legitimate topic words (e.g. "殺人事件") collide with hate/harassment
/// patterns under the prior single-list design.
///
/// Declared `nonisolated` so ``ContentFilter`` (itself `nonisolated +
/// Sendable`) can access ``inputPatterns`` / ``outputPatterns`` without
/// crossing a MainActor boundary under the project's
/// `SWIFT_DEFAULT_ACTOR_ISOLATION = MainActor`.
nonisolated enum ContentBlocklist {
  /// The schema version this loader expects. Bumping requires a migration.
  static let expectedSchemaVersion: Int = 1

  /// Patterns evaluated by the input validator (excludes `violence`).
  ///
  /// Crashes via ``preconditionFailure`` if the post-partition list is
  /// empty — that would silently disable the input layer, which is the
  /// silent-degradation class ADR-005 §4.4 explicitly named.
  static let inputPatterns: [String] = {
    let result =
      bundledEntries
      .filter { !categoriesExcludedFromInput.contains($0.contentCategory) }
      .map(\.term)
    precondition(
      !result.isEmpty,
      "ContentBlocklist.inputPatterns is empty after partition — check categoriesExcludedFromInput vs source.json categories"
    )
    return result
  }()

  /// Patterns evaluated by the output filter (all categories).
  static let outputPatterns: [String] = bundledEntries.map(\.term)

  /// Cached entries loaded from `.main` once.
  ///
  /// Hidden behind a static-let so the JSON parse runs at most once per
  /// process even though both ``inputPatterns`` and ``outputPatterns``
  /// derive from it.
  private static let bundledEntries: [BlockedPattern] = entries(from: .main)

  // MARK: - Policy

  /// Categories that the input validator MUST NOT enforce.
  ///
  /// Per ADR-005 §10.1 (2026-04-27): `violence` is excluded so authors can
  /// write ethics / roleplay scenarios about combat or harm without
  /// tripping the authoring filter. Output filter still catches this
  /// category to preserve defense-in-depth on LLM-generated text.
  private static let categoriesExcludedFromInput: Set<BlockedCategory> = [
    .violence
  ]

  // MARK: - Loading

  /// Loads parsed blocklist entries from the given bundle.
  ///
  /// - Parameter bundle: Bundle to load from. Production uses `.main`;
  ///   tests pass `Bundle(for: DatabaseManager.self)` to point at the
  ///   host-app bundle (mirroring the ``PresetLoader`` pattern).
  /// - Returns: Decoded entries.
  ///
  /// Crashes via ``preconditionFailure`` on:
  /// - missing or unreadable resource
  /// - malformed JSON
  /// - schema version mismatch
  /// - unknown ``BlockedCategory`` value
  /// - empty `patterns` array
  ///
  /// All five are build-config / data-curation bugs that should fail at
  /// launch, not silently degrade to an empty filter.
  static func entries(from bundle: Bundle) -> [BlockedPattern] {
    guard
      let url = bundle.url(forResource: "ContentBlocklist", withExtension: "json"),
      let data = try? Data(contentsOf: url)
    else {
      preconditionFailure(
        "ContentBlocklist.json missing or unreadable in bundle \(bundle.bundleIdentifier ?? "<unknown>")"
      )
    }
    do {
      return try decode(data)
    } catch {
      preconditionFailure("Failed to decode ContentBlocklist.json: \(error)")
    }
  }

  /// Parses raw JSON data into a list of blocklist entries.
  ///
  /// Extracted from ``entries(from:)`` so the parser can be unit-tested
  /// with inline fixtures without a bundle round-trip. Throws rather than
  /// crashes here so tests can assert specific failure modes; the
  /// production callsite in ``entries(from:)`` converts to
  /// ``preconditionFailure``.
  static func decode(_ data: Data) throws -> [BlockedPattern] {
    let envelope = try JSONDecoder().decode(Envelope.self, from: data)
    guard envelope.version == expectedSchemaVersion else {
      throw DecodeError.versionMismatch(found: envelope.version, expected: expectedSchemaVersion)
    }
    guard !envelope.patterns.isEmpty else {
      throw DecodeError.emptyPatterns
    }
    return envelope.patterns
  }

  /// Errors thrown by ``decode(_:)`` for testable failure modes.
  ///
  /// Malformed JSON and unknown ``BlockedCategory`` values surface as
  /// `Swift.DecodingError` from `JSONDecoder` rather than this enum.
  enum DecodeError: Error {
    case versionMismatch(found: Int, expected: Int)
    case emptyPatterns
  }

  // MARK: - Envelope

  private struct Envelope: Decodable {
    let version: Int
    let patterns: [BlockedPattern]
  }
}
