package com.pastura.models

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Cross-language YAML-roundtrip-fidelity harness — Issue #220 W4 PR-C
 * (Pattern 1).
 *
 * **Question discharged**: does `snakeyaml-engine-kmp` (Kotlin) parse the
 * bundled preset YAML to the SAME tree that Swift's `Yams` produces? This is
 * the spike's Tier-4 "YAML roundtrip fidelity: snakeyaml-engine-kmp vs current
 * Yams output" learning-capture item, and the YAML axis of H2 (semantic
 * equivalence). It complements the JSON axis already covered by
 * [CanonicalEquivalenceTests].
 *
 * **The two inputs (both FROZEN at the same point in time):**
 * - The preset YAML, committed as `jvmTest/resources/frozen-presets/<preset>.yaml`.
 *   These are frozen copies of `Pastura/Pastura/Resources/Presets/<preset>.yaml`
 *   as of the KMP-spike merge base (`f73bc48`) — the exact revision the Swift
 *   baseline below was generated from.
 * - The Swift/Yams lossless parse, committed as
 *   `commonTest/resources/yaml-baselines/<preset>.yaml.json`, generated by
 *   Swift `RoundtripHelper.encodedYamlShapeBaseline`.
 *
 * **Why frozen and not read from the live presets (#501 Stage 1):** the Swift
 * baseline can only be regenerated by the Swift-side Roundtrip harness, which
 * Stage 1 does not land (dead-sandbox / not-production-wired — the harness
 * returns with the K/N consumer at Stage 2/5). Reading the live presets would
 * therefore make this equivalence check go red — with no in-Stage-1 way to
 * refresh the Swift baseline — the moment any preset is edited (3 of these 4
 * had already drifted between `f73bc48` and the Stage-1 landing). Freezing both
 * sides keeps the point-in-time cross-language guarantee intact and drift-proof.
 * Re-validating the CURRENT presets against a regenerated Swift baseline is a
 * Stage-2/5 task (tracked on #501). Parser health against the live presets is
 * covered, drift-immunely, by [LivePresetParseSmokeTests].
 *
 * **This is the LOSSLESS raw-parse shape** (`agents` / `output` / `words` /
 * `probability` / nested `conditional`), structurally DISTINCT from
 * `baselines/<preset>.json` (the lossy `ScenarioLoader` output that
 * [CanonicalEquivalenceTests] consumes). The two must not be conflated.
 *
 * **Observation window**: both trees are run through [Canonicalizer] (Stage
 * 1+2 — key-sort + null-omit), so key-ORDER and explicit-null divergence are
 * intentionally OUT of scope (neither parser emits explicit nulls for these
 * presets anyway). What remains observable, and is the real fidelity signal:
 * scalar TYPE (int vs float vs bool vs string), scalar TEXT, and tree
 * STRUCTURE. [wordWolfRawScalarTypesAreNotLaundered] additionally asserts on
 * the RAW (pre-canonicalize) trees so the type claim is not silently laundered
 * through canonicalization.
 *
 * **Lives in `jvmTest/`** (not `commonTest/`): reads both the frozen preset and
 * the baseline resources via `getResourceAsStream` — a JVM-only API. Mirrors
 * [CanonicalEquivalenceTests]'s placement rationale.
 */
class YamlFidelityEquivalenceTests {

    private val json = Json { ignoreUnknownKeys = true }

    private val codec: YamlCodec = YamlCodec.default()

    // -------- inputs --------

    private fun frozenPreset(presetName: String): String {
        val path = "/frozen-presets/$presetName.yaml"
        val stream = YamlFidelityEquivalenceTests::class.java.getResourceAsStream(path)
            ?: error("Missing frozen preset: $path (see class doc — frozen at f73bc48)")
        return stream.bufferedReader(Charsets.UTF_8).use { it.readText() }
    }

    /** The Swift/Yams lossless parse, committed under `yaml-baselines/`. */
    private fun swiftYamsBaseline(presetName: String): JsonElement {
        val path = "/yaml-baselines/$presetName.yaml.json"
        val stream = YamlFidelityEquivalenceTests::class.java.getResourceAsStream(path)
            ?: error("Missing YAML-shape baseline: $path (regenerate via RoundtripBaselineTests)")
        val text = stream.bufferedReader(Charsets.UTF_8).use { it.readText() }
        return json.parseToJsonElement(text)
    }

    private fun canonicalText(tree: JsonElement): String =
        json.encodeToString(JsonElement.serializer(), Canonicalizer.canonicalize(tree))

    private fun assertYamlFidelity(presetName: String) {
        val kotlinParse = codec.decode(frozenPreset(presetName))
        val swiftParse = swiftYamsBaseline(presetName)
        assertEquals(
            canonicalText(swiftParse),
            canonicalText(kotlinParse),
            "snakeyaml-engine-kmp must parse $presetName.yaml to the same canonical " +
                "tree as Swift Yams (Tier-4 YAML fidelity / H2 YAML axis)",
        )
    }

    // -------- per-preset cross-language fidelity (4 base ja presets) --------

    @Test fun prisonersDilemmaYamlFidelity() = assertYamlFidelity("prisoners_dilemma")

    @Test fun wordWolfYamlFidelity() = assertYamlFidelity("word_wolf")

    @Test fun boketeYamlFidelity() = assertYamlFidelity("bokete")

    @Test fun targetScoreRaceYamlFidelity() = assertYamlFidelity("target_score_race")

    // -------- raw-tree scalar-type guard (anti-laundering) --------

    /**
     * Asserts scalar TYPE fidelity on the RAW (pre-canonicalize) trees, so the
     * per-preset equivalence tests above cannot pass by laundering a type
     * mismatch through canonicalization.
     *
     * `word_wolf.yaml` is the only base preset carrying both a genuine boolean
     * (`exclude_self: true`) and a float (`probability: 0.5`). The boolean is
     * the load-bearing case: Swift's Yams bridges scalars through `NSNumber`,
     * so a missing `is Bool` guard in the dumper would launder `true` into `1`.
     * If that regressed, the Swift baseline would carry `1` (int) while
     * snakeyaml keeps `true` (bool) — caught here, not as an opaque byte-diff.
     */
    @Test
    fun wordWolfRawScalarTypesAreNotLaundered() {
        val kotlinParse = codec.decode(frozenPreset("word_wolf"))
        val swiftParse = swiftYamsBaseline("word_wolf")

        // `exclude_self: true` must be a JSON boolean on BOTH sides, not `1`.
        assertEquals(JsonPrimitive(true), findFirst(kotlinParse, "exclude_self"))
        assertEquals(JsonPrimitive(true), findFirst(swiftParse, "exclude_self"))

        // `probability: 0.5` float text must match (not `1` / `0.50`).
        assertEquals("0.5", (findFirst(kotlinParse, "probability") as? JsonPrimitive)?.content)
        assertEquals("0.5", (findFirst(swiftParse, "probability") as? JsonPrimitive)?.content)
    }

    /** First value reachable under [key] anywhere in [tree] (DFS), or null. */
    private fun findFirst(tree: JsonElement, key: String): JsonElement? = when (tree) {
        is JsonObject -> tree[key] ?: tree.values.firstNotNullOfOrNull { findFirst(it, key) }
        is JsonArray -> tree.firstNotNullOfOrNull { findFirst(it, key) }
        else -> null
    }
}
