package com.pastura.models

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Cross-language YAML-roundtrip-fidelity harness — Issue #220 W4 PR-C
 * (Pattern 1).
 *
 * **Question discharged**: does `snakeyaml-engine-kmp` (Kotlin) parse the
 * bundled preset YAML to the SAME tree that Swift's `Yams` produces? This is
 * the spike's Tier-4 "YAML roundtrip fidelity: snakeyaml-engine-kmp vs current
 * Yams output" learning-capture item, and the YAML axis of H2 (semantic
 * equivalence). It complements the JSON axis already covered by
 * [CanonicalEquivalenceTests].
 *
 * **The two inputs (single source of truth):**
 * - The LIVE preset YAML at `Pastura/Pastura/Resources/Presets/<preset>.yaml`,
 *   read via the `pastura.presetsDir` system property injected by the `jvmTest`
 *   task (see `shared/models/build.gradle.kts`). No copy of the YAML is kept in
 *   the module — the live file is read directly, so it cannot drift.
 * - The Swift/Yams lossless parse, committed as
 *   `commonTest/resources/yaml-baselines/<preset>.yaml.json`, generated by
 *   `RoundtripHelper.encodedYamlShapeBaseline` and drift-guarded by
 *   `RoundtripBaselineTests.yamlShapeBaselineMatchesCommitted`.
 *
 * **This is the LOSSLESS raw-parse shape** (`agents` / `output` / `words` /
 * `probability` / nested `conditional`), structurally DISTINCT from
 * `baselines/<preset>.json` (the lossy `ScenarioLoader` output that
 * [CanonicalEquivalenceTests] consumes). The two must not be conflated.
 *
 * **Observation window**: both trees are run through [Canonicalizer] (Stage
 * 1+2 — key-sort + null-omit), so key-ORDER and explicit-null divergence are
 * intentionally OUT of scope (neither parser emits explicit nulls for these
 * presets anyway). What remains observable, and is the real fidelity signal:
 * scalar TYPE (int vs float vs bool vs string), scalar TEXT, and tree
 * STRUCTURE. [wordWolfRawScalarTypesAreNotLaundered] additionally asserts on
 * the RAW (pre-canonicalize) trees so the type claim is not silently laundered
 * through canonicalization.
 *
 * **Lives in `jvmTest/`** (not `commonTest/`): reads baseline resources via
 * `getResourceAsStream` and the live preset via `java.io.File` — both JVM-only
 * APIs. Mirrors [CanonicalEquivalenceTests]'s placement rationale.
 */
class YamlFidelityEquivalenceTests {

    private val json = Json { ignoreUnknownKeys = true }

    private val codec: YamlCodec = YamlCodec.default()

    // -------- inputs --------

    private fun liveYaml(presetName: String): String {
        val dir = System.getProperty("pastura.presetsDir")
            ?: error(
                "Missing `pastura.presetsDir` system property — the jvmTest task " +
                    "must inject it (see shared/models/build.gradle.kts).",
            )
        val file = File(dir, "$presetName.yaml")
        assertTrue(file.exists(), "Missing live preset YAML: ${file.path}")
        return file.readText(Charsets.UTF_8)
    }

    /** The Swift/Yams lossless parse, committed under `yaml-baselines/`. */
    private fun swiftYamsBaseline(presetName: String): JsonElement {
        val path = "/yaml-baselines/$presetName.yaml.json"
        val stream = YamlFidelityEquivalenceTests::class.java.getResourceAsStream(path)
            ?: error("Missing YAML-shape baseline: $path (regenerate via RoundtripBaselineTests)")
        val text = stream.bufferedReader(Charsets.UTF_8).use { it.readText() }
        return json.parseToJsonElement(text)
    }

    private fun canonicalText(tree: JsonElement): String =
        json.encodeToString(JsonElement.serializer(), Canonicalizer.canonicalize(tree))

    private fun assertYamlFidelity(presetName: String) {
        val kotlinParse = codec.decode(liveYaml(presetName))
        val swiftParse = swiftYamsBaseline(presetName)
        assertEquals(
            canonicalText(swiftParse),
            canonicalText(kotlinParse),
            "snakeyaml-engine-kmp must parse $presetName.yaml to the same canonical " +
                "tree as Swift Yams (Tier-4 YAML fidelity / H2 YAML axis)",
        )
    }

    // -------- per-preset cross-language fidelity (4 base ja presets) --------

    @Test fun prisonersDilemmaYamlFidelity() = assertYamlFidelity("prisoners_dilemma")

    @Test fun wordWolfYamlFidelity() = assertYamlFidelity("word_wolf")

    @Test fun boketeYamlFidelity() = assertYamlFidelity("bokete")

    @Test fun targetScoreRaceYamlFidelity() = assertYamlFidelity("target_score_race")

    // -------- raw-tree scalar-type guard (anti-laundering) --------

    /**
     * Asserts scalar TYPE fidelity on the RAW (pre-canonicalize) trees, so the
     * per-preset equivalence tests above cannot pass by laundering a type
     * mismatch through canonicalization.
     *
     * `word_wolf.yaml` is the only base preset carrying both a genuine boolean
     * (`exclude_self: true`) and a float (`probability: 0.5`). The boolean is
     * the load-bearing case: Swift's Yams bridges scalars through `NSNumber`,
     * so a missing `is Bool` guard in the dumper would launder `true` into `1`.
     * If that regressed, the Swift baseline would carry `1` (int) while
     * snakeyaml keeps `true` (bool) — caught here, not as an opaque byte-diff.
     */
    @Test
    fun wordWolfRawScalarTypesAreNotLaundered() {
        val kotlinParse = codec.decode(liveYaml("word_wolf"))
        val swiftParse = swiftYamsBaseline("word_wolf")

        // `exclude_self: true` must be a JSON boolean on BOTH sides, not `1`.
        assertEquals(JsonPrimitive(true), findFirst(kotlinParse, "exclude_self"))
        assertEquals(JsonPrimitive(true), findFirst(swiftParse, "exclude_self"))

        // `probability: 0.5` float text must match (not `1` / `0.50`).
        assertEquals("0.5", (findFirst(kotlinParse, "probability") as? JsonPrimitive)?.content)
        assertEquals("0.5", (findFirst(swiftParse, "probability") as? JsonPrimitive)?.content)
    }

    /** First value reachable under [key] anywhere in [tree] (DFS), or null. */
    private fun findFirst(tree: JsonElement, key: String): JsonElement? = when (tree) {
        is JsonObject -> tree[key] ?: tree.values.firstNotNullOfOrNull { findFirst(it, key) }
        is JsonArray -> tree.firstNotNullOfOrNull { findFirst(it, key) }
        else -> null
    }
}
